//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por ESTRUCTURAS DE DATOS.rc
//
#define TEX_NombreMedico                1
#define BTN_DarAltaMedic                2
#define TEX_Cedula                      3
#define SDLG_REGISTROCONSULTAS          9
#define SDLG_REGISTROMEDICOS            101
#define IDR_MENU1                       103
#define SDLG_REGISTROPACIENTE           104
#define SDLG_ESPECIALIDADES             108
#define SGDL_CitaMedico                 110
#define SDLG_EspecialidadSemanaMes      112
#define SDLG_ConsultaSemanaMes          114
#define SDLG_RegistroCita               116
#define SDLG_INCIARSESION               118
#define SDLG_ALTASBAJASCAMBIOS          120
#define TEX_Pacientes                   1001
#define TEX_TelefonoPaciente            1002
#define CB_PacientesConsul              1003
#define TEX_Pacientes2                  1003
#define CB_MedicoConsul                 1004
#define IDC_COMBO3                      1005
#define CB_SEMANAFILTRO3                1005
#define CB_NuevaHora                    1005
#define CB_Hora2                        1006
#define BTN_CargarImagen                1007
#define TEX_Edad                        1008
#define RD_Lunes                        1009
#define RD_Masculino                    1010
#define RD_Femenino                     1011
#define RD_Consultorio2                 1012
#define RD_Consultorio3                 1013
#define TEX_FechaConsul                 1015
#define TEX_Descripcion                 1016
#define CB_Minutos                      1017
#define CB_EspecialidadesConsul         1018
#define CB_Minutos2                     1019
#define BTN_DarAltaCita                 1021
#define BTN_DarAltaPaciente             1022
#define CB_Especialidades               1023
#define RD_Consultorio1                 1024
#define TEX_Telefono                    1026
#define CB_Horas                        1027
#define RD_Tarde                        1028
#define RD_Manana                       1029
#define RD_Jueves                       1030
#define TEX_FechaPaciente               1031
#define CB_PrimerMedic                  1032
#define BTN_VOLVERE                     1034
#define TEX_NewEspecialidad             1035
#define IDA                             1036
#define TEX_DescripcionEspecialidad     1037
#define BTN_ACEPTARE                    1038
#define BTM_ImageMedic                  1040
#define BTN_ACEPTARMEDICOMES            1041
#define CB_MEDICOSYMES                  1042
#define CB_MESFILTRO3                   1043
#define CB_PacienteALTAS                1044
#define CB_RegistrosALTAS               1045
#define BTN_Despliegue                  1048
#define EST_FechaRE                     1049
#define EST_HORARIORE                   1050
#define EST_HORAB                       1051
#define EST_MINUTOSB                    1052
#define EST_ESPECIALIDAD                1053
#define EST_HORARIORE2                  1054
#define EST_HORAB2                      1055
#define IDC_LIST1                       1056
#define EST_MINUTOSB2                   1056
#define EST_Consultorio                 1057
#define BTN_Despliegue2                 1058
#define EST_MEDICOS                     1059
#define EST_Horario                     1060
#define EST_InfoConsultorio             1061
#define EST_InfoHorario                 1062
#define BTM_ImgMedCon                   1063
#define EST_Martes                      1064
#define CHK_Martes                      1065
#define CHK_Jueves                      1066
#define EST_Viernes                     1067
#define EST_DIA                         1068
#define EST_Disponibilidad              1069
#define EST_NOCHE                       1070
#define EST_TURNO                       1071
#define CB_MesesFiltro                  1072
#define CB_MesConsul2                   1073
#define CB_SemanaConsul2                1074
#define CB_EspecialidadFiltro           1075
#define BTM_ACEPTARSEMANAMES            1076
#define BTN_ESPECIALIDADGUARDAR         1077
#define CB_Cedula                       1078
#define BTM_ImageMedic2                 1080
#define INF_NUMEROCITA                  1081
#define INF_FECHAREGISTRO               1082
#define INF_HORAREGISTRO                1083
#define INF_MINUTOSREGISTRO             1084
#define INF_CONSULTORIOREGISTRO         1085
#define INF_ESPECIALIDADREGISTRO        1086
#define INF_MEDICOREGISTRO              1087
#define INF_PACIENTEREGISTRO            1088
#define INF_TELEFONOREGISTRO            1089
#define INF_ESTADOREGISTRO              1090
#define BTM_IMAGENTEGISTRO              1091
#define EDIT_NOMBREINICIAR              1092
#define EDIT_CONTRASENAINICIAR2         1093
#define BTN_DespliegueREGISTROS         1093
#define TEX_NUMERODECITA                1094
#define BTN_INICIARSESION               1095
#define BTN_CargarInformacion           1096
#define CB_EspecialidadALTAS            1097
#define BTN_MODIFICARESPECIALIDADES     1098
#define BTN_ELIMINARESPECIALIDAD        1099
#define BTN_MODIFICARMEDICOS            1100
#define BTN_ELIMINARMEDICO              1101
#define TEX_NuevaEspecialidad           1102
#define TEX_NuevaDescripcion            1103
#define BTN_CARGARNUEVAFOTOMEDICO       1104
#define CB_NuevoMinutos                 1105
#define BTN_MODIFICARPACIENTES          1107
#define BTN_ELIMINARPACIENTE            1108
#define EST_NuevaDescripcion            1109
#define EST_NuevaEspecialidad           1110
#define BTN_MODIFICARREGISTROS          1111
#define BTN_ELIMINARREGISTRO            1112
#define EST_NuevoNombreMedico           1113
#define EST_NuevoTelefonoMedico         1115
#define EST_NuevoConsultorioMedico      1116
#define EST_NuevoEspecialidadMedico     1117
#define EST_NuevoHorarioMedico          1118
#define EST_NuevoDiasMedico             1119
#define TEX_NuevoNombreMedico           1120
#define TEX_NuevoTelefonoMedico         1122
#define RA_NuevoConsultorio3            1123
#define CB_NuevasEspecialidadMedico     1124
#define RA_NuevoConsultorio2            1125
#define RA_NuevoConsultorio1            1126
#define CHECK_LUNESMEDICOS              1127
#define DATE_FechaNacimientoPaciente    1128
#define IMG_NUEVAIMAGENMEDICO           1129
#define EST_NUEVOPACIENTE               1130
#define RAD_NuevoTarde                  1131
#define RAD_NuevoManana                 1132
#define CHECK_MARTESMEDICOS             1133
#define CHECK_MIERCOLESMEDICOS          1134
#define CHECK_JUEVESMEDICOS             1135
#define CHECK_VIERNESMEDICOS            1136
#define TEX_NuevoPaciente               1137
#define TEX_NuevaEdad                   1138
#define TEX_NuevaDescripcionPa          1139
#define CB_NuevaMedicoRecomendadoPa     1140
#define RAD_NUEVOFEMENINO               1141
#define RAD_NUEVOMASCULINO              1142
#define CB_NuevoPacienteRe              1143
#define CB_NuevoEspecialidadRe          1144
#define CB_NuevoMedicoRe                1145
#define BTN_NuevoDespliegue             1146
#define BTN_NuevoDespliegue2            1147
#define EST_NUEVOGENERO                 1148
#define EST_NUEVAFECHANACIMIENTO        1149
#define EST_NUEVAEDAD                   1150
#define EST_NUEVOMEDICORECOMENDADO      1151
#define EST_NUEVADESCRIPCIONPA          1152
#define EST_NuevoPacienteRe             1153
#define EST_NuevoEspecialidadRe         1154
#define EST_NuevoMedicoRe               1155
#define EST_TELEFONOPACIENTE            1156
#define TEX_NuevoTelefonoPaciente       1158
#define EST_NUEVOLUNES                  1159
#define EST_NUEVOMARTES                 1160
#define EST_NUEVOMIERCOLES              1161
#define EST_NUEVOJUEVES                 1162
#define EST_NUEVOVIERNES                1163
#define ESTNUEVOCONSULTORIORE           1164
#define EST_nuevaEspecialidad2          1165
#define DATE_NUEVAFECHA                 1166
#define EST_HORARIOTARDE                1167
#define EST_HORARIOMANANA               1168
#define BTN_VOLVERMEDICOS               1169
#define EST_APELLIDOPACIENTE            1170
#define INFAPELLIDOSPACIENTE            1171
#define IDC_RADIO1                      1172
#define CB_MedicosALTAS                 2000
#define ID_GuardarSALIR                 6928
#define CB_Hora                         10055
#define CHK_Lunes                       10633
#define EST_Miercoles                   10653
#define EST_Jueves                      10663
#define CHK_Miercoles                   10673
#define CHK_Viernes                     10683
#define ID_REGISTROMEDICOS              40001
#define ID_REGISTRODEPACIENTES          40002
#define ID_REGISTROCITAS                40003
#define ID_REGISTROSMEDICOS             40004
#define ID_CONSULTACITAS                40005
#define ID_REGISTRODEMEDICOS_A40006     40006
#define ID_REGISTRODEMEDICOS_A40007     40007
#define ID_ESPECIALIDAD                 40008
#define ID_CONSULTADECITAS_MEDICOYMES   40009
#define ID_CONSULTADECITAS_SEMANAYMES   40010
#define ID_CONSULTADECITAS_ESPECIALIDADYSEMANADELMES 40011
#define ID_SALIR_GUARDARDATOSYSALIR     40012
#define ID_ConsultaCitas2               40014
#define ID_BAJASCAMBIOS                 40015
#define EST_Lunes                       41298

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1173
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
